name: MDVTools
version: 1.0.4
main: com.mdvcraft.tools.MDVToolsPlugin
api-version: '1.21'
author: MDVCRAFT
description: Herramientas de profesión para MDVCRAFT.
softdepend: [MDVHeadOres, MMOItems]
commands:
  mdvtools:
    description: Comandos administrativos de MDVTools.
    usage: /mdvtools reload
    permission: mdvtools.admin
permissions:
  mdvtools.admin:
    description: Permite recargar MDVTools.
    default: op
